[package]
name = "audiograph-examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cpal_sine"
path = "cpal_sine.rs"

[dependencies]
audiograph = { path = "../lib" }
clap = { version = "4.5.45", features = ["derive"] }
cpal = "0.16.0"
